kind = "mobile"
previewPath = "/aorane-mobile/"
title = "AORANE Mobile App"
version = "1.0.0"
id = "artifacts/aorane-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
localPort = 8081

[services.development]
run = "node web-server.js"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aorane-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/aorane-mobile", "run", "serve" ]

[services.env]
PORT = "8081"
BASE_PATH = "/"
