const colors = {
  light: {
    text: "#0A0F1E",
    tint: "#00BFA6",
    background: "#F0F4F8",
    foreground: "#0A0F1E",
    card: "#FFFFFF",
    cardForeground: "#0A0F1E",
    primary: "#00BFA6",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5F3",
    secondaryForeground: "#00897B",
    muted: "#E5EAF0",
    mutedForeground: "#6B7280",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDE3EC",
    input: "#DDE3EC",
    success: "#10B981",
    warning: "#F59E0B",
    surface: "#FFFFFF",
    tealLight: "#E0F7F4",
    purpleLight: "#EDE9FE",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#00BFA6",
    background: "#0A0F1E",
    foreground: "#F9FAFB",
    card: "#141C2E",
    cardForeground: "#F9FAFB",
    primary: "#00BFA6",
    primaryForeground: "#0A0F1E",
    secondary: "#1A2640",
    secondaryForeground: "#00D4B8",
    muted: "#1F2937",
    mutedForeground: "#9CA3AF",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1F2937",
    input: "#1F2937",
    success: "#10B981",
    warning: "#F59E0B",
    surface: "#141C2E",
    tealLight: "#0D2B28",
    purpleLight: "#1E1340",
  },
  radius: 16,
};

export default colors;
