import { motion } from "framer-motion";
import {
  MessageSquare,
  Barcode,
  FileText,
  Utensils,
  Stethoscope,
  Users,
  CreditCard,
  Zap,
} from "lucide-react";

const upcoming = [
  {
    icon: MessageSquare,
    color: "#25D366",
    bg: "linear-gradient(135deg, #25D36615 0%, #22C55E10 100%)",
    border: "#25D36630",
    tag: "Next Release",
    tagColor: "#15803d",
    tagBg: "#DCFCE7",
    title: "WhatsApp Health Bot",
    desc: "Log food, water & exercise by just sending a WhatsApp message. Bot reminds you for medicines, sends evening calorie update — like a personal health assistant on your favourite app.",
    points: ["Food log via chat", "Medicine & water reminders", "Weekly report on WhatsApp", "Zero app-open needed"],
    plan: "Pro Plan",
  },
  {
    icon: Barcode,
    color: "#F97316",
    bg: "linear-gradient(135deg, #F9731615 0%, #FB923C10 100%)",
    border: "#F9731630",
    tag: "Next Release",
    tagColor: "#c2410c",
    tagBg: "#FFF7ED",
    title: "Packaged Food Scanner",
    desc: "Scan the barcode on any biscuit, chips, juice, or packaged snack. Nutrition data from the FSSAI database loads instantly — no AI cost, no manual typing, just scan and done.",
    points: ["Instant FSSAI database lookup", "Maggi, chips, drinks — all covered", "Saves AI cost for common foods", "Works offline too"],
    plan: "All Plans",
  },
  {
    icon: FileText,
    color: "#3B82F6",
    bg: "linear-gradient(135deg, #3B82F615 0%, #60A5FA10 100%)",
    border: "#3B82F630",
    tag: "Coming Soon",
    tagColor: "#1d4ed8",
    tagBg: "#EFF6FF",
    title: "Weekly Health Report",
    desc: "Every Sunday morning, receive a beautifully designed health summary — weekly calories, macros, exercise minutes, stress levels, and personalized AI insight — delivered on WhatsApp and email automatically.",
    points: ["Auto-generated every Sunday", "AI-written personal insight", "WhatsApp + Email delivery", "Compare with previous week"],
    plan: "Pro & Max",
  },
  {
    icon: Utensils,
    color: "#8B5CF6",
    bg: "linear-gradient(135deg, #8B5CF615 0%, #A78BFA10 100%)",
    border: "#8B5CF630",
    tag: "Coming Soon",
    tagColor: "#6d28d9",
    tagBg: "#F5F3FF",
    title: "AI Diet Chart Generator",
    desc: "Tell Aorane your goal — weight loss, diabetes management, muscle gain — and get a personalized 7-day Indian meal plan with breakfast, lunch, dinner, and snacks. Generated by AI, reviewed by nutrition science.",
    points: ["Goal-based meal planning", "Indian food — roti, dal, sabzi", "Adjusts for allergies & conditions", "Regenerate anytime"],
    plan: "Premium",
  },
  {
    icon: Stethoscope,
    color: "#EF4444",
    bg: "linear-gradient(135deg, #EF444415 0%, #F8717110 100%)",
    border: "#EF444430",
    tag: "Q3 2026",
    tagColor: "#b91c1c",
    tagBg: "#FFF1F2",
    title: "Doctor & Dietitian Connect",
    desc: "Book a 30-min consultation with verified dietitians and doctors directly through Aorane. They see your full health history — no need to explain everything from scratch. Prescriptions synced to your app.",
    points: ["Verified Indian dietitians", "Health data auto-shared", "Prescription auto-sync", "Affordable video consults"],
    plan: "Max Plan",
  },
  {
    icon: Users,
    color: "#0EA5E9",
    bg: "linear-gradient(135deg, #0EA5E915 0%, #38BDF810 100%)",
    border: "#0EA5E930",
    tag: "Q3 2026",
    tagColor: "#0369a1",
    tagBg: "#F0F9FF",
    title: "Family Plan (5 Members)",
    desc: "One subscription, five family members. Track parents' medicines, children's nutrition, and spouse's fitness goals — all from one dashboard. Ideal for Indian joint families.",
    points: ["5 members, 1 subscription", "Individual profiles & goals", "Shared family health dashboard", "Elder care reminders"],
    plan: "Max Plan",
  },
];

export default function UpcomingSection() {
  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8 bg-[#FAFAFA]">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <span className="inline-flex items-center gap-1.5 text-xs font-bold px-3 py-1 rounded-full uppercase tracking-widest mb-3"
            style={{ background: "#FEF3C7", color: "#92400E", border: "1px solid #FCD34D" }}>
            <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
            Upcoming Features
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mt-2">
            What's coming{" "}
            <span className="gradient-text">very soon</span>
          </h2>
          <p className="mt-3 text-gray-500 max-w-xl mx-auto text-sm">
            We're building India's most complete health platform — here's what's on the roadmap. Early access for Pro users.
          </p>
        </motion.div>

        {/* Cards grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {upcoming.map((item, i) => (
            <motion.div
              key={item.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.07 }}
              className="rounded-2xl border p-5 relative overflow-hidden flex flex-col gap-3 card-hover"
              style={{ background: item.bg, borderColor: item.border }}
            >
              {/* Tag */}
              <div className="flex items-center justify-between">
                <span
                  className="text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wide"
                  style={{ background: item.tagBg, color: item.tagColor }}
                >
                  {item.tag}
                </span>
                <span
                  className="text-[10px] font-semibold px-2 py-0.5 rounded-full"
                  style={{ background: item.color + "15", color: item.color }}
                >
                  {item.plan}
                </span>
              </div>

              {/* Icon + Title */}
              <div className="flex items-center gap-3">
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                  style={{ background: item.color }}
                >
                  <item.icon className="w-5 h-5 text-white" />
                </div>
                <h3 className="text-sm font-extrabold text-gray-900 leading-snug">{item.title}</h3>
              </div>

              {/* Desc */}
              <p className="text-xs text-gray-600 leading-relaxed">{item.desc}</p>

              {/* Points */}
              <ul className="space-y-1 mt-auto">
                {item.points.map((pt) => (
                  <li key={pt} className="flex items-center gap-1.5 text-xs text-gray-700">
                    <span className="w-3.5 h-3.5 rounded-full flex items-center justify-center shrink-0"
                      style={{ background: item.color + "20" }}>
                      <span className="w-1.5 h-1.5 rounded-full" style={{ background: item.color }} />
                    </span>
                    {pt}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

        {/* Bottom CTA strip */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.3 }}
          className="mt-10 rounded-2xl p-5 flex flex-col sm:flex-row items-center justify-between gap-4"
          style={{
            background: "linear-gradient(135deg, #1A1A2E 0%, #16213E 100%)",
          }}
        >
          <div>
            <p className="text-xs font-bold text-orange-400 mb-1">🎯 Be the first to get early access</p>
            <h3 className="text-base font-extrabold text-white">
              Download Aorane free — unlock features as they launch
            </h3>
            <p className="text-xs text-white/50 mt-0.5">
              Pro users get all upcoming features first. Free users get core features always.
            </p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <a
              href="https://play.google.com/store"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold transition-all hover:scale-105 active:scale-95"
              style={{ background: "#E85D26", color: "white" }}
            >
              <Zap className="w-4 h-4" />
              Download Free
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
