import { Brain, Eye, UserCheck, AlertTriangle, ListChecks, Scale, RefreshCw, Mail } from "lucide-react";
import {
  LegalLayout, SectionBlock, SubSection, BulletList, Tag, InfoBox, WarningBox, ContactBlock,
  type LegalSectionMeta,
} from "@/components/legal/LegalLayout";

const sections: LegalSectionMeta[] = [
  { id: "overview",   num: "01", title: "Overview",                       icon: Brain,       accent: "#0747A6" },
  { id: "where",      num: "02", title: "Where AI Is Used",               icon: ListChecks,  accent: "#0747A6" },
  { id: "nodecisions", num: "03", title: "No Automated Decisions With Legal Effect", icon: Scale, accent: "#059669" },
  { id: "oversight",  num: "04", title: "Human Oversight & Your Control", icon: UserCheck,   accent: "#0747A6" },
  { id: "limitations", num: "05", title: "Known Limitations",             icon: AlertTriangle, accent: "#D97706" },
  { id: "transparency", num: "06", title: "Transparency Commitment",      icon: Eye,         accent: "#0747A6" },
  { id: "changes",    num: "07", title: "Changes to This Disclosure",     icon: RefreshCw,   accent: "#0747A6" },
  { id: "contact",    num: "08", title: "Contact Information",          icon: Mail,        accent: "#00B388" },
];

export default function AiDisclosurePage() {
  return (
    <LegalLayout
      path="/ai-disclosure"
      title="AI & Automated Processing Disclosure"
      metaDescription="AORANE AI Disclosure — where and how we use AI to process your health data, what it does and doesn't decide, and your right to human review."
      badge="GDPR Art. 22 & EU AI Act Transparency Aligned"
      badgeIcon={Brain}
      lastUpdated="August 2026"
      heroTags={<>
        <Tag color="#059669">No Automated Diagnosis</Tag>
        <Tag color="#0747A6">Human-Reviewable</Tag>
      </>}
      sections={sections}
    >
      <SectionBlock {...sections[0]}>
        <p>
          Aorane uses artificial intelligence to help you understand your health and wellness data. This page
          explains, in plain language, where AI is involved, what it does, and — most importantly — what it does
          <strong> not</strong> decide on its own. It supplements Section 4 ("AI & Automated Processing") of our{" "}
          <a href="/terms" className="font-semibold text-blue-700 hover:underline">Terms of Service</a> and Section 4
          of our <a href="/privacy" className="font-semibold text-blue-700 hover:underline">Privacy Policy</a>.
        </p>
      </SectionBlock>

      <SectionBlock {...sections[1]}>
        <BulletList items={[
          "Food-photo analysis — estimating food items and nutritional content from a photo you upload",
          "Medical/diagnostic report analysis — extracting structured values (e.g. lab results) from a document you upload",
          "Health Score & wellness insights — combining your logged data into a summary indicator and suggestions",
          "Weekly diet chart and daily suggestion generation",
        ]} />
      </SectionBlock>

      <SectionBlock {...sections[2]}>
        <InfoBox badge="This Is the Core Commitment">
          Aorane's AI does not make any decision that produces a legal effect on you or similarly significantly
          affects you — it does not diagnose disease, approve or deny any service, set your insurance or pricing
          terms, or make a healthcare decision on your behalf. Every AI output on Aorane is informational, and every
          consequential action (what you eat, what medication you take, whether to see a doctor) remains yours to
          take.
        </InfoBox>
      </SectionBlock>

      <SectionBlock {...sections[3]}>
        <BulletList items={[
          "You choose whether to upload a food photo or medical report for AI analysis — it is never automatic or required",
          "You can view, edit, or delete any AI-generated entry (e.g. correct a misidentified food item) before it's saved to your log",
          "You can request a human look at how a specific AI output was generated by contacting support — see Section 8 below",
          "You can stop using any AI-powered feature at any time without losing access to manually-entered tracking",
        ]} />
      </SectionBlock>

      <SectionBlock {...sections[4]}>
        <WarningBox>
          AI systems can produce inaccurate, incomplete, or misleading output ("hallucinations"). Food recognition,
          nutrition estimates, and medical report extraction are automated best-effort estimates — verify anything
          important with a qualified healthcare professional before acting on it. See Section 4 of our Terms of
          Service for the full disclaimer.
        </WarningBox>
      </SectionBlock>

      <SectionBlock {...sections[5]}>
        <p>We do not use your uploaded photos, medical reports, or health data to train any third-party AI provider's foundation models. AI/ML inference providers are engaged as processors under the terms described in our <a href="/sub-processors" className="font-semibold text-blue-700 hover:underline">Sub-processor List</a> and, where applicable, a signed Data Processing Agreement.</p>
      </SectionBlock>

      <SectionBlock {...sections[6]}>
        <p>As AI regulation evolves (e.g. the EU AI Act's phased obligations through 2026–2027, and emerging U.S. state AI-transparency laws), we will update this disclosure to reflect any material change in how AI is used or in the rights available to you.</p>
      </SectionBlock>

      <SectionBlock {...sections[7]}>
        <p>Questions about a specific AI-generated result, or want a human to review it? Contact us at:</p>
        <ContactBlock />
      </SectionBlock>
    </LegalLayout>
  );
}
